# 1 引入numpy并查看版本
```
out:1.17.3
```

In [2]:
import numpy as np

# 2 创建一位数组，0-9
```
out:array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

# 3 创建boolean数组（3x3全部为True）
```
out:array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])
```

# 4 提取满足条件的元素（提取奇数项）
```
in:    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out:   array([1, 3, 5, 7, 9])
```

In [3]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 5 替换满足条件的元素（替换奇数项为-1）
```
in: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out:array([0, -1, 2, -1, 4, -1, 6, -1, 8, -1])
```

In [4]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 6 与5相同，但是不要在原数组上改动，返回个新的数组

In [5]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 7 reshape一个数组（0-9这个一维数组->2x5的二维数组）
```
in: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out: array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])
```

# 8 垂直拼接俩数组
```
in: a = np.arange(10).reshape(2,-1)
   b = np.repeat(1, 10).reshape(2,-1)
out: array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])
```

In [6]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# 9 水平拼接俩数组
```
in: a = np.arange(10).reshape(2,-1)
   b = np.repeat(1, 10).reshape(2,-1)
out: array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
```

In [7]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# 10 生成自定义的数组
```
in: a = np.array([1,2,3])
out: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [8]:
a = np.array([1,2,3])

# 11 求两数组交集
```
in: a = np.array([1,2,3,2,3,4,3,4,5,6])
   b = np.array([7,2,10,2,7,4,9,4,9,8])
out:array([2, 4])
```

In [9]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# 12 从一个数组中删除另一个数组中含有的元素
```
in: a = np.array([1,2,3,4,5])
   b = np.array([5,6,7,8,9])
out:array([1,2,3,4])
```

In [10]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# 13 两等长数组，找出位置相同且值也相同的下标
```
in: a = np.array([1,2,3,2,3,4,3,4,5,6])
   b = np.array([7,2,10,2,7,4,9,4,9,8])
out:(array([1, 3, 5, 7]),)
```

In [11]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# 14 提取给定范围的数据(提取值在5-10之间的元素)
```
in: a = np.array([2, 6, 1, 9, 10, 3, 27])
out:(array([6, 9, 10]),)
```

In [12]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

# 15 取a,b两等长数组中较大值为新数组
```
in: a = [4,6,1,7,9]
b=[1,6,9,2,7]
```

In [13]:
a = [4,6,1,7,9]
b=[1,6,9,2,7]

# 16 如何交换二维数组两列（交换3x3数组的第0和第1列）
```
in:arr = np.arange(9).reshape(3,3)
out:array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])
       ```

In [14]:
arr = np.arange(9).reshape(3,3)

# 17 如何交换二维数组两行（交换3x3数组第0和第1行）
```
in:arr = np.arange(9).reshape(3,3)
out:array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])
```

In [15]:
arr =np.arange(9).reshape(3,3)

# 18 如何反转二维数组的行
```
in:arr = np.arange(9).reshape(3,3)
out:array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])
```

In [16]:
arr =np.arange(9).reshape(3,3)

# 19  如何反转二维数组的列
```
in:arr = np.arange(9).reshape(3,3)
out:array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])
       ```

In [17]:
arr =np.arange(9).reshape(3,3)

# 20 创建5x3的float二维数组，值是5-10的随机数

# 21 [打印设置相关]float数组每个元素保留小数点后3位打印(只是打印时，本质不变)
```
in:rand_arr = np.random.random((5,3))
```

In [19]:
rand_arr = np.random.random((5,3))

# 22 [打印设置相关]避免科学计数法打印数组
```
in:np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
```

In [20]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3

# 23 [打印设置相关]如何限制数组打印条数
```
in:a = np.arange(15)
out: array([ 0,  1,  2, ..., 12, 13, 14])
```

In [21]:
a = np.arange(15)

# 24 [打印设置相关]如何打印全部数据避免被省略

# 25 导入含有数字和文本的数据集，保证数据完整(不要让文本变nan了)
```
in:url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
```

In [22]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

# 26 一维tuple数组，提取特定一列
```
in:url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
```

In [23]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


# 27 如何将一维tuple数组转二维
```
in:同26
```

In [24]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


# 28 计算数组均值、中位数、标准差
```
in: np.arange(1000)
out:499.5 499.5 288.6749902572095
```

In [25]:
a = np.arange(1000)

# 29 数组归一化
```
in:a = np.arange(15)
a = a.reshape(3,5)
out:array([[0.      , 0.071429, 0.142857, 0.214286, 0.285714],
       [0.357143, 0.428571, 0.5     , 0.571429, 0.642857],
       [0.714286, 0.785714, 0.857143, 0.928571, 1.      ]])
```

In [26]:
a = np.arange(15)
a = a.reshape(3,5)

# 30 如何计算softmax分数

# 31找到第5%和第95%大的值

```
in:a = np.random.rand(100)
```

In [27]:
a = np.random.rand(100)

# 32 如何在随机位置改值，在一个数组中随机10个位置改为nan
```
in: a = np.random.rand(100)
```

In [28]:
a = np.random.rand(100)

# 33 找出数组中nan的位置
```
in: a = np.random.rand(100)
a[np.random.randint(100, size=20)] = np.nan
out: 20
```

In [29]:
a = np.random.rand(100)
a[np.random.randint(100, size=20)] = np.nan

# 34 使用2个或以上条件来过滤数组元素
```
in: a = np.random.rand(100)
out:在>0.2 且 <0.8
```

In [30]:
a = np.random.rand(100)

# 35 删除含有nan的行
```
in:a = np.random.rand(100)
a[np.random.randint(100, size=4)] = np.nan
a = a.reshape(10,10)
```

In [31]:
a = np.random.rand(100)
a[np.random.randint(100, size=4)] = np.nan
a = a.reshape(10,10)

# 36 求两列相关性(如第0和第2列相关性)
```
in:a = np.random.rand(100)
a = a.reshape(10,10)
```

In [32]:
a = np.random.rand(100)
a = a.reshape(10,10)

# 37 判断数组是否有nan值
```
in:a = np.random.rand(100)
a[np.random.randint(100, size=4)] = np.nan
a = a.reshape(10,10)
```

In [33]:
a = np.random.rand(100)
a[np.random.randint(100, size=4)] = np.nan
a = a.reshape(10,10)

# 38 将数组中的nan全部替换为0

In [34]:
a = np.random.rand(100)
a[np.random.randint(100, size=4)] = np.nan
a = a.reshape(10,10)

# 39 求数组不重复值个数
```
in: a = np.random.rand(100)
a[np.random.randint(100, size=4)] = np.nan
a = a.reshape(10,10)
a = a*10
a = a.astype('int16')
```

In [35]:
a = np.random.rand(100)
a[np.random.randint(100, size=4)] = np.nan
a = a.reshape(10,10)
a = a*10
a = a.astype('int16')

# 40 数字转文本（0-3转s，4-6转m，7-9转l）
```
a = np.random.rand(100)
a = a.reshape(10,10)
a = a*10
a = a.astype('int16')
```

In [36]:
a = np.random.rand(100)
a[np.random.randint(100, size=4)] = np.nan
a = a.reshape(10,10)
a = a*10
a = a.astype('int16')

# 41 用现有的列，创建新的一列（第0列叫x,第1列叫y，新增 sin(pi*(x/100)) * y^2）
```
a = np.random.rand(100)
a = a.reshape(10,10)
a = a*10
a = a.astype('int16')
```

In [37]:
a = np.random.rand(100)
a = a.reshape(10,10)
a = a*10
a = a.astype('int16')

# 42 从1d数组中抽样选出10个元素
```
in:a = np.random.rand(100)
a = a*10
a = a.astype('int16')
```


In [38]:
a = np.random.rand(100)
a = a*10
a = a.astype('int16')

# 43 如何获取1d数组中不重复的第二大的值
```
in:a = np.random.rand(100)
a = a*10
a = a.astype('int16')
```

In [39]:
a = np.random.rand(100)
a = a*10
a = a.astype('int16')

# 44 依据某一列对2d数组排序(例如根据第0列排序)
```
in:a = np.random.rand(100)
a = a*10
a = a.astype('int16')
a = a.reshape(10,10)
```

In [40]:
a = np.random.rand(100)
a = a*10
a = a.astype('int16')
a = a.reshape(10,10)


# 45 众数
```
in:a = np.random.rand(100)
a = a*10
a = a.astype('int16')
a = a.reshape(10,10)
```

In [41]:
a = np.random.rand(100)
a = a*10
a = a.astype('int16')
a = a.reshape(10,10)

# 46 找出比给定值大的数第一次出现的位置
```
in:a = np.random.rand(100)
a = a*10
a = a.astype('int16')

b = 5
```

In [42]:
a = np.random.rand(100)
a = a*10
a = a.astype('int16')
b = 5

# 47 将所有>7的替换为7，<3的替换为3
```
in:a = np.random.rand(100)
a = a*10
a = a.astype('int16')
a = a.reshape(10,10)
```

In [43]:
a = np.random.rand(100)
a = a*10
a = a.astype('int16')
a = a.reshape(10,10)


# 48 获取1d数组topK大的值（例如k=5）
```
a = np.random.uniform(1,50, 20)
```

In [44]:
a = np.random.uniform(1,50, 20)


# 50 如何把数组的数组转为1d数组
```
# Input:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
```

In [45]:
# Input:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])


# 51 为数组的每个元素生成二进制编码
```
in: a = np.array([2, 3, 2, 2, 2, 1])
out:array([[ 0.,  1.,  0.],
        [ 0.,  0.,  1.],
        [ 0.,  1.,  0.],
        [ 0.,  1.,  0.],
        [ 0.,  1.,  0.],
        [ 1.,  0.,  0.]])
```

In [46]:
a = np.array([2, 3, 2, 2, 2, 1])

# 52 分好组的元素给定组内行号
```
in: a = np.array(['a','a','a','b','b','c','c','c','c'])
out: array([0,1,2,0,1,0,1,2,3])
```

In [47]:
a = np.array(['a','a','a','b','b','c','c','c','c'])

# 53 分好组的元素每组给个标号
```
in: a = np.array(['a','a','a','b','b','c','c','c','c'])
out: array([0,0,0,1,1,2,2,2,2])
```

In [48]:
a = np.array(['a','a','a','b','b','c','c','c','c'])

# 54 给出每个元素在排序后的位置下标数组
```
in: [ 9  4 15  0 17 16 17  8  9  0]
out: [4 2 6 0 8 7 9 3 5 1]
```

In [49]:
np.random.seed(10)
a = np.random.randint(20, size=10)

# 55 上题改成多维数组
```
in:np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)

out:#> [[4 2 6 0 8]
#>  [7 9 3 5 1]]
```

In [50]:
# Input:
np.random.seed(10)
a = np.random.randint(20, size=[2,5])

# 56 二维数组找出每一行的最大值
```
# Input
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a
```

In [51]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])

# 57 上题变种，计算每一行max/min的值

In [52]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])

# 58 找到数组中重复的值
```
in: [0 0 3 0 2 4 2 2 2 2]
out:[False  True False  True False False  True  True  True  True]
```

In [53]:
# Input
np.random.seed(100)
a = np.random.randint(0, 5, 10)

# 60 将一张jpg图片转换为numpy数组
```
in:URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'
```

In [54]:
URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'

# 61 如何剔除所有nan值
```
in:np.array([1,2,3,np.nan,5,6,7,np.nan])
out:array([ 1.,  2.,  3.,  5.,  6.,  7.])
```

In [55]:
a = np.array([1,2,3,np.nan,5,6,7,np.nan])

# 62 如何计算两数组欧式距离
```
in:a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
out:6.7082039324993694
```

In [56]:
# Input
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

# 63 一维数组找到所有峰值(比前后都大的值)的下标
```
in:a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
out:[2,5]
```

In [57]:
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])

# 64 二维数组每一行都减去一个一维数组
```
in:a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
  b_1d = np.array([1,2,3])
  
 out: [
     [2,1,0],
     [3,2,1],
     [4,3,2]
 ]
```

In [58]:
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])

# 65 找到第n个特定数出现的下标
```
找第5个1出现的位置
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
```

In [59]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

# 66 将datetime64类型转datetime类型
```
in:dt64 = np.datetime64('2018-02-25 22:10:10')
```

In [60]:
dt64 = np.datetime64('2018-02-25 22:10:10')

# 67 计算滑动窗口均值(例如窗口大小3，就是0-2均值，1-3均值，2-4....)
```
in:np.random.seed(100)
Z = np.random.randint(10, size=10)

out:[ 6.33  6.    5.67  4.67  3.67  2.    3.67  3.  ]
```

In [61]:
np.random.seed(100)
Z = np.random.randint(10, size=10)

# 68 创建一个等差数列初值5增幅3数组总长10

# 69 如何在一系列无序日期中，补全缺失的日期


In [62]:
# Input
dates = np.arange(np.datetime64('2018-02-01'), np.datetime64('2018-02-25'), 2)
print(dates)


['2018-02-01' '2018-02-03' '2018-02-05' '2018-02-07' '2018-02-09'
 '2018-02-11' '2018-02-13' '2018-02-15' '2018-02-17' '2018-02-19'
 '2018-02-21' '2018-02-23']


# 70 给定一维数组，创建阶梯型二维数组，二维数组列数是4，步幅是2
```
in:arr = np.arange(15) 
out:#> [[ 0  1  2  3]
#>  [ 2  3  4  5]
#>  [ 4  5  6  7]
#>  [ 6  7  8  9]
#>  [ 8  9 10 11]
#>  [10 11 12 13]]
```

In [64]:
arr = np.arange(15) 